version: 2
updates:
  - package-ecosystem: github-actions
    directory: ./typescript
    schedule:
      interval: daily
    commit-message:
      prefix: "[dep]"

  - package-ecosystem: npm
    directory: ./typescript
    schedule:
      interval: daily
