name: Build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout main
        uses: actions/checkout@v6

      - name: npm install
        run: |
          npm install

      - name: npm run all
        run: |
          npm run all

      - name: Commit Check (builtin SimpleTag)
        uses: ./
        with:
          validator: "simpletag"

      - name: Commit Check (builtin RegEx)
        if: success() || failure()
        uses: ./
        with:
          validator: "regex"
          options: |
            summary: ".*"
            description: ".*"

      - name: Commit Check (custom validator)
        if: success() || failure()
        uses: ./
        with:
          validator_file: "example/simpletag.mjs"
