name: Build
on: [push, pull_request]

jobs:
  build-gha:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v6

      - name: npm install
        working-directory: ./typescript
        run: |
          npm install
      - name: npm run all
        working-directory: ./typescript
        run: |
          npm run all
      - name: Commit Check (shipped SimpleTag)
        uses: ./
        with:
          validator: "SimpleTag"
      - name: Commit Check (shipped RegEx)
        if: success() || failure()
        uses: ./
        with:
          validator: "RegEx"
          options: |
            >any<
            >any<
      - name: Commit Check (local)
        if: success() || failure()
        uses: ./
        with:
          validator_file: "typescript/example/simpleTag.mjs"
